type=command

echo "--------------Start to Execute DWT To ADS For Active Users Last Three Consecutive Weeks Action-----------------"
echo "-----------API-> http://172.12.0.7:8089/api/v1/etl/ads/threeConsecutiveWeeks--------"

command=curl -X GET "http://172.12.0.7:8089/api/v1/etl/ads/threeConsecutiveWeeks" -H "accept: */*"

echo "--------------End to Execute DWT To ADS For Active Users Last Three Consecutive Weeks Action-----------------"

dependencies=AzkabanJob-START-DWS-to-DWT