type=command

echo "--------------Start to Execute DWT To ADS For Number Of Returning Users Action-----------------"
echo "-----------API-> http://172.12.0.7:8089/api/v1/etl/ads/returningUsers--------"

command=curl -X GET "http://172.12.0.7:8089/api/v1/etl/ads/returningUsers" -H "accept: */*"

echo "--------------End to Execute DWT To ADS For Number Of Returning Users Action-----------------"

dependencies=AzkabanJob-START-DWS-to-DWT