type=command

echo "--------------Start to Execute DWT To ADS For Number Of Silent Users Action-----------------"
echo "-----------API-> http://172.12.0.7:8089/api/v1/etl/ads/numberOfSilentUsers--------"

command=curl -X GET "http://172.12.0.7:8089/api/v1/etl/ads/numberOfSilentUsers" -H "accept: */*"

echo "--------------End to Execute DWT To ADS For Number Of Silent Users Action-----------------"

dependencies=AzkabanJob-START-DWS-to-DWT