type=command

echo "--------------Start to Execute DWT To ADS For Number Of New Device Added Daily Action-----------------"
echo "-----------API-> http://172.12.0.7:8089/api/v1/etl/ads/newDeviceAddedDaily--------"

command=curl -X GET "http://172.12.0.7:8089/api/v1/etl/ads/newDeviceAddedDaily" -H "accept: */*"

echo "--------------End to Execute DWT To ADS For Number Of New Device Added Daily Action-----------------"

dependencies=AzkabanJob-START-DWS-to-DWT