type=command

echo "--------------Start to Execute DWT To ADS For Daily User Retention Status Action-----------------"
echo "-----------API-> http://172.12.0.7:8089/api/v1/etl/ads/dailyUserRetentionStatus--------"

command=curl -X GET "http://172.12.0.7:8089/api/v1/etl/ads/dailyUserRetentionStatus" -H "accept: */*"

echo "--------------End to Execute DWT To ADS For Daily User Retention Status Action-----------------"

dependencies=AzkabanJob-START-DWS-to-DWT