type=command

echo "--------------Start to Execute DWT To ADS For Active Devices Action-----------------"
echo "-----------API-> http://172.12.0.7:8089/api/v1/etl/ads/activeDevices--------"

command=curl -X GET "http://172.12.0.7:8089/api/v1/etl/ads/activeDevices" -H "accept: */*"

echo "--------------End to Execute DWT To ADS For Active Devices Action-----------------"

dependencies=AzkabanJob-START-DWS-to-DWT